### ISSUE TITLE
Could reduce minimum deployment target to iOS 10?

### ISSUE THREAD

**Issue by Yehsam23** [livekit/client-sdk-ios#2]
The minimum deployment target of "Package.swift" is v13 (iOS 13.0)

Can be set to v10, because our project is currently set to 10.0

Thanks

**Comment by davidzhao** [comment]
hi @Yehsam23, unfortunately it's not simple to do that. we are using several features that are only available in later builds:

- NWPathMonitor: requires iOS 12
- WebSocket client: requires iOS 13

It might be possible to remove both of these requirements, but unfortunately we don't have any cycles to investigate at the moment.
