### ISSUE TITLE
Can not build on xCode 12.1.

### ISSUE THREAD

**Issue by nguyenductai** [livekit/client-sdk-ios#8]
After add swift package, in the RoomViewController.swift file can not find the LiveKit:
import LiveKit  -> no such module 'LikeKit'

Please help, I tried a lot but still fails.
Thanks.

**Comment by hiroshihorie** [comment]
Hi @nguyenductai , Can I have more information ? Can you make sure you have `LiveKit` in your `Frameworks` 
 located at Targets > General page.
<img width="660" alt="スクリーンショット 2021-10-06 6 18 46" src="https://user-images.githubusercontent.com/548776/136104326-02e1d040-b266-45b5-9362-33037e304ef9.png">
